# Generated by Django 3.2.15 on 2022-08-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_logmodel'),
        ('auditlog', '0011_logentry_serialized_data'),
    ]

    operations = [
    ]
