# Generated by Django 3.2.15 on 2023-04-11 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0012_merge_0009_logmodel_0011_logentry_serialized_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogModel',
        ),
        migrations.CreateModel(
            name='ElasticLogEntryModel',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Elastic Log Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
    ]
