# Generated by Django 4.2.13 on 2024-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0013_delete_log_model_add_elastic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElasticLogEntryModel',
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['content_type', 'object_id'], name='auditlog_lo_content_254308_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['content_type', 'object_pk'], name='auditlog_lo_content_751382_idx'),
        ),
    ]
