# Generated by Django 4.2.15 on 2025-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0014_delete_elasticlogentrymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='additional_data',
            field=models.JSONField(blank=True, help_text="Additional data to store in the log entry. Can be returned by 'get_additional_data' method of log entry object", null=True, verbose_name='additional data'),
        ),
    ]
